### ISSUE TITLE
PEP440 pypi error

### ISSUE THREAD

**Issue by Adamtaranto** [Adamtaranto/frisk#14]
>>> python setup.py sdist upload -r pypi
Upload failed (400): Invalid version, cannot use PEP 440 local versions on PyPI.
error: Upload failed (400): Invalid version, cannot use PEP 440 local versions on PyPI.

**Comment by Adamtaranto** [comment]
Pypi does not allow local version names. Wil fix by incrementing version number after next batch of fixes.

**Comment by kdmurray91** [comment]
Yeah, definitely increment the version num. Sorry, I missed that you hadn't.

Cheers,
K

On 21:24 27/10, Adam Taranto wrote:
> Pypi does not allow local version names. Wil fix by incrementing version number after next batch of fixes.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Adamtaranto/frisk/issues/14#issuecomment-151718075

---
Kevin Murray

GPG pubkey: http://www.kdmurray.id.au/static/A4B4EE6A.asc
FPR: 656C 0632 1EAB 2C3F 3837  9767 17C2 8EB1 A4B4 EE6A

**Comment by Adamtaranto** [comment]
Fixed.
