### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Adamtaranto** [Adamtaranto/frisk#6]
Needs documentation. Should include: 
What is Frisk?
How to cite
How it works?
Installing dependencies 
Examples / Use cases
Interpreting output

**Comment by kdmurray91** [comment]
Fixed RTFD.org: was trying to install things from requirements.txt, so that it failed when hmmlearn couldn't install due to cython. We don't need any of that to build the docs, so just used /dev/null as the requirements file
